export const MAKE_WIDGETS = 'MAKE_WIDGETS';
export const SELL_WIDGETS = 'SELL_WIDGETS';
export const HIRE_WORKER_DRONE = 'HIRE_WORKER_DRONE';
export const HIRE_SALES_DRONE = 'HIRE_SALES_DRONE';
export const UPDATE = 'UPDATE';
